### PR TITLE
[IOTDB-108]Fix mistakes in doc

### PR DESCRIPTION
**Pull request by fanhualta**
Corresponding Jira issue link: https://issues.apache.org/jira/browse/IOTDB-108

### CODE REVIEW

**Comment by FLOW4215** [comment]
There are another 5 mistake : "(oen or more)" in this doc.
Please fix them too.
Thanks!

image

**Comment by fanhualta** [comment]
> There are another 5 mistake : "(oen or more)" in this doc.
> Please fix them too.
> Thanks!
> 
> image

fixed

**Comment by FLOW4215** [comment]
the other mistake you found “double ‘’the‘’” is also happened in these 5 lines too.
image

**Comment by fanhualta** [comment]
> the other mistake you found “double ‘’the‘’” is also happened in these 5 lines too.
> image

fixed

**Pull request merged**
