### PR TITLE
[IOTDB-877] fix prefix bug on show storage group and show devices

### PR DESCRIPTION
**Pull request by yhwang-hbl**

### CODE REVIEW

**Review by Alima777 — APPROVED** [review]
LGTM.

**Review by neuyilan — APPROVED** [review]

**Comment by neuyilan** [comment]
The CI failed, please take a look

**Comment by yhwang-hbl** [comment]
> The CI failed, please take a look

I ran the server integration test locally and it was successful,Therefore, I think 1 failure check may be due to unstable CI

**Comment by samperson1997** [comment]
> > The CI failed, please take a look
> 
> I ran the server integration test locally and it was successful,Therefore, I think 1 failure check may be due to unstable CI

Hi, I re-ran it for you : )

**Comment by yhwang-hbl** [comment]
> > > The CI failed, please take a look
> > 
> > 
> > I ran the server integration test locally and it was successful,Therefore, I think 1 failure check may be due to unstable CI
> 
> Hi, I re-ran it for you : )

Thank you very much.

**Pull request merged**
