### PR TITLE
[IOTDB-881] Fix Double quotes bug in Align by device

### PR DESCRIPTION
**Pull request by Alima777**
This pr fixes:

1. **IOTDB-881 bug:** Double quoted meaurement is recognized as constant in Align by device. Only single quoted measurement should be recognized as constant after double quotes can be used in path.

2. Modify splitPathToDetachedPath() method: support nested double quotes now.

3. Extract some logic in PhysicalGenerator transfrom() method.

### CODE REVIEW

**Comment by Genius-pig** [comment]
Can you add support nested double quotes in `Path`?

**Review by qiaojialin — COMMENTED** [review]
Update the user guide

**Comment by Alima777** [comment]
> Can you add support nested double quotes in `Path`?

Hi, thank you for reminding.

**Comment by Alima777** [comment]
> Update the user guide

Updated.

**Review by Genius-pig — APPROVED** [review]

**Review by qiaojialin — APPROVED** [review]
Could the split method in MetaUtils and Path be combined?

**Pull request merged**
