### PR TITLE
[IOTDB-91] Improve tsfile-spark-connector to support spark 2.4.3

### PR DESCRIPTION
**Pull request by samperson1997**
Improve tsfile-spark-connector to support spark 2.4.3 as is mentioned in [issue IOTDB-91](https://issues.apache.org/jira/browse/IOTDB-91).

Spark has [decoupled internal Row from external Row](https://github.com/apache/spark/pull/6792),  which influences _TsFileWriterFactory_ (extends _OutputWriterFactory_) and _TsFileOutputWriter_ (extends _OutputWriter_). Therefore, function _toTsRecord_ has to change param type from _Row_ to _InternalRow_.

### CODE REVIEW

**Comment by LeiRui** [comment]
I tried spark2.4 spark-shell and the read task failed:

`supportDataType(Lorg/apache/spark/sql/types/DataType;Z)Z`

Btw, the tsfile to be read was created using the `TsFileWrite.java` in the `tsfile/example` directory.

I then turned to spark2.3 spark-shell and this time the read task passed but the write task failed still:

`Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1661)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1649)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1648)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1648)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:831)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:831)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1882)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1831)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1820)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:642)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:2034)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:194)
  ... 72 more
Caused by: org.apache.spark.SparkException: Task failed while writing rows.
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:285)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:197)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:196)
  at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
  at org.apache.spark.scheduler.Task.run(Task.scala:109)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriterFactory.getFileExtension(Lorg/apache/hadoop/mapreduce/TaskAttemptContext;)Ljava/lang/String;
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.newOutputWriter(FileFormatWriter.scala:361)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.execute(FileFormatWriter.scala:378)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:269)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask$3.apply(FileFormatWriter.scala:267)
  at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1415)
  at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:272)
  ... 8 more`

**Comment by LeiRui** [comment]
The commands I used in the spark-shell:
```
import org.apache.iotdb.tsfile._
val df = spark.read.tsfile("testDirect.tsfile") 
df.show
df.write.tsfile("output")
```

**Comment by samperson1997** [comment]
> The commands I used in the spark-shell:
> 
> ```
> import org.apache.iotdb.tsfile._
> val df = spark.read.tsfile("testDirect.tsfile") 
> df.show
> df.write.tsfile("output")
> ```

Hi,

I have tried the same file created by `TsFileWrite.java`, and the commands of reading and writing all passed. I thought the failure may be caused by inconsistent spark version: the spark version should be updated to 2.3 / 2.4, and the `tsfile-spark-connector-0.8.0-SNAPSHOT.jar` needs to be built again with the accordingly spark version in pom.xml.

**Comment by LeiRui** [comment]
> > The commands I used in the spark-shell:
> > ```
> > import org.apache.iotdb.tsfile._
> > val df = spark.read.tsfile("testDirect.tsfile") 
> > df.show
> > df.write.tsfile("output")
> > ```
> 
> Hi,
> 
> I have tried the same file created by `TsFileWrite.java`, and the commands of reading and writing all passed. I thought the failure may be caused by inconsistent spark version: the spark version should be updated to 2.3 / 2.4, and the `tsfile-spark-connector-0.8.0-SNAPSHOT.jar` needs to be built again with the accordingly spark version in pom.xml.

Tests pass successfully.

**Pull request merged**
