### PR TITLE
Used to change Magic String to last version

### PR DESCRIPTION
**Pull request by Genius-pig**
Used to Change Magic String to last version. If you want to know more about it, saw [this](https://issues.apache.org/jira/browse/IOTDB-165).

### CODE REVIEW

**Comment by Genius-pig** [comment]
@jixuan1989 Thanks, it may take me some days to finish it.

**Comment by jixuan1989** [comment]
Hi Zhu, can you just remove SNAPSHOT in this PR? 
For others, we can do it in the future.

**Comment by Genius-pig** [comment]
@jixuan1989 Have changed it.

**Comment by jixuan1989** [comment]
Hi Zhu,

Jialin and I have a discussion and record them on the JIRA:
- https://issues.apache.org/jira/browse/IOTDB-165

So, can you just change this PR by: 
- just remain the changes about TestHelper.java and Utils.java.

If you want, you can follow the idea on the JIRA to add compatibility feature.

**Comment by Genius-pig** [comment]
@jixuan1989 Have done and fix some grammar mistake.

**Pull request merged**
