### PR TITLE
let the dockerfile build from iotdb v0.8

### PR DESCRIPTION
**Pull request by jixuan1989**
for testing, please see #69

### CODE REVIEW

**Comment by jixuan1989** [comment]
well... `docker build` failed because:
```
Downloading from central: https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/2.11.6/scala-library-2.11.6.pom (1.4 kB at 3.4 kB/s)
[ERROR] error: scala.reflect.internal.MissingRequirementError: object java.lang.Object in compiler mirror not found.
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:17)
[ERROR] 	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:18)
[ERROR] 	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:53)
```

I think it is because the version problem of scala.

**Comment by jixuan1989** [comment]
@samperson1997  can you have a look?

**Comment by samperson1997** [comment]
> @samperson1997 can you have a look?

Hi, by upgrading the scala version, there won't be errors during downloading, but some other errors will happen when building spark-tsfile module:
>[ERROR] Failed to execute goal on project spark-tsfile: Could not resolve dependencies for project org.apache.iotdb:spark-tsfile:jar:0.8.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.spark:spark-core_2.11:jar:2.4.3, org.apache.spark:spark-sql_2.11:jar:2.4.3, org.apache.spark:spark-catalyst_2.11:jar:2.4.3, org.apache.parquet:parquet-column:jar:1.10.1, org.apache.parquet:parquet-encoding:jar:1.10.1, org.apache.parquet:parquet-hadoop:jar:1.10.1, org.apache.parquet:parquet-format:jar:2.4.0, org.apache.parquet:parquet-jackson:jar:1.10.1, org.apache.arrow:arrow-vector:jar:0.10.0, org.apache.arrow:arrow-format:jar:0.10.0, org.apache.arrow:arrow-memory:jar:0.10.0, com.carrotsearch:hppc:jar:0.7.2, com.vlkan:flatbuffers:jar:1.2.0-3f79e055, org.scala-lang:scala-library:jar:2.11.8, org.scalatest:scalatest_2.11:jar:3.0.5, org.scalactic:scalactic_2.11:jar:3.0.5, org.scala-lang:scala-reflect:jar:2.11.12, org.scala-lang.modules:scala-xml_2.11:jar:1.0.6: Could not transfer artifact org.apache.spark:spark-core_2.11:jar:2.4.3 from/to central (https://repo.maven.apache.org/maven2): GET request of: org/apache/spark/spark-core_2.11/2.4.3/spark-core_2.11-2.4.3.jar from central failed: Premature end of Content-Length delimited message body (expected: 13513957; received: 7159590 -> [Help 1]

I'll focus on this error now.

**Comment by samperson1997** [comment]
Spark-tsfile module is avoided to be compiled by [PR #308](https://github.com/apache/incubator-iotdb/pull/308).

**Pull request merged**
