### PR TITLE
Add Grafana IoTDB Bridge Artefact to distrbution in tools/grafana fol…

### PR DESCRIPTION
**Pull request by JulianFeinauer**
…der.

NOTE: Should also be picked to develop.

### CODE REVIEW

**Comment by JulianFeinauer** [comment]
@chrisdutz thanks for the hint I changed it to use the dependencySet. You can have a look if you like :)

**Comment by chrisdutz** [comment]
LGTM now :-)

**Comment by jixuan1989** [comment]
LGTM.
Chris is an expert of Maven... If he says "LGTM", it really looks good for how to use Maven :D

**Comment by JulianFeinauer** [comment]
Oh, sorry too late @jixuan1989. We could do separate downloads if we use multiple assembly files. Then user can decide what to download. Thats the way to go, I guess?

**Comment by jixuan1989** [comment]
It is ok. I have approved it...

Maybe we can separate it in v0.10 and release more connectors at that time.

**Comment by JulianFeinauer** [comment]
+1. So I do not pick it for master, yet?
WDYT? (currently about to do that :) ).

**Comment by jixuan1989** [comment]
If we can not implement separating these binaries into several files quickly, I think we can pick this commit to master... to keep consistent between 0.9 and the master branch...
And then consider separating them as a new feature. 
How do you think?

**Comment by jixuan1989** [comment]
Besides, when we are in the incubator, there is an issue that we can retain at most 10 files. Otherwise, there will be a warning on this page to say incubator project can have at most 10 files, please delete stale version files: http://incubator.apache.org/clutch/iotdb.html (the Release Chapter).

**Pull request merged**
