### PR TITLE
[IOTDB-156]add -e option for iotdb client

### PR DESCRIPTION
**Pull request by EJTTianYu**

### CODE REVIEW

**Comment by jixuan1989** [comment]
1. the title of this PR should be modified: please add jira issue number at the head of the title (besides, you may need to add a link manually on that issue on JIRA)

2. please have a look at the travis result, failed at IoTDBConfigDynamicAdapterTest 
https://travis-ci.org/apache/incubator-iotdb/jobs/563361930
I will restart the test once again.

**Comment by jixuan1989** [comment]
Besides, seems there is no UT for the new feature.

**Comment by jt2594838** [comment]
+1

**Comment by FLOW4215** [comment]
We have tested this feature in EJTTianYu's branch.
It works fine.

**Comment by jixuan1989** [comment]
But no document...

**Pull request merged**
