### PR TITLE
[IOTDB-892] Replace fastjson with Gson

### PR DESCRIPTION
**Pull request by yuqi1129**

### CODE REVIEW

**Comment by jixuan1989** [comment]
1. please notice the CI.
2. can you introduce more about what benefit we can get from this replacement?

**Comment by yuqi1129** [comment]
@jixuan1989 OK

**Comment by qiaojialin** [comment]
Hi, please pay attention to the ci. The IoTDBMetadataFetchIT.databaseMetaDataTest failed.

**Comment by yuqi1129** [comment]
OK, i will do it after when i get off work today

Jialin Qiao <notifications@github.com> 于2020年9月14日周一 下午5:00写道：

**Review by qiaojialin — COMMENTED** [review]
Hi, please fix the conflict

**Comment by yuqi1129** [comment]
@qiaojialin , OK, i have updated the code,  can anyone help to review the code ？

**Review by jixuan1989 — COMMENTED** [review]
reviewed and I think the changes are ok.

The only concern is that I do not know the implementation of GSON so I do not know whether using a GSON instance in MTree has a performance problem. (GSON is thread-safety).

**Review by qiaojialin — APPROVED** [review]
LGTM, JSON format in MTree is nearly never used. The metadata query of JDBC need to reconstruct and the toJSON in MTree is most possible to be discarded...

**Pull request merged**
