### PR TITLE
remove echo in cli

### PR DESCRIPTION
**Pull request by Ring-k**

### CODE REVIEW

**Comment by jixuan1989** [comment]
why use Scanner to replace ConsoleReader? Any benefit?

**Comment by Ring-k** [comment]
> why use Scanner to replace ConsoleReader? Any benefit?

ConsoleReader will repeat the input.

**Comment by qiaojialin** [comment]
> why use Scanner to replace ConsoleReader? Any benefit?

The repeat is like this:

image

**Comment by jixuan1989** [comment]
Hi, do we revert this PR? 
Now we can not use "up arrow" in the console, which is worse than print the command one more time..

**Pull request merged**
