### PR TITLE
[IOTDB-128] Fix links of nav content in documents

### PR DESCRIPTION
**Pull request by samperson1997**
Fix links of nav content in documents by turning nav content into "Overview" part to fix the bug proposed in [issue IOTDB-128](https://issues.apache.org/jira/browse/IOTDB-128).

### CODE REVIEW

**Comment by Genius-pig** [comment]
Sorry for troubling you. To be honest, I don't think you have fixed this bug. Because the original purpose was when you click some tables of contents(TOC),  jump to the appropriate contents.  Rather than just adding an "outline" in the head of contents.

**Comment by samperson1997** [comment]
> Sorry for troubling you. To be honest, I don't think you have fixed this bug. Because the original purpose was when you click some tables of contents(TOC), jump to the appropriate contents. Rather than just adding an "outline" in the head of contents.

Hi,

We have considered the original purpose, but we thought the nav-content in the head of the documents is not as convenient as on side part (as User Guide documents), so I changed it into "outline" now. Nav content on side part will probably be added in the future. Maybe I should change my description of this PR?

**Comment by Genius-pig** [comment]
> > Sorry for troubling you. To be honest, I don't think you have fixed this bug. Because the original purpose was when you click some tables of contents(TOC), jump to the appropriate contents. Rather than just adding an "outline" in the head of contents.
> 
> Hi,
> 
> We have considered the original purpose, but we thought the nav-content in the head of the documents is not as convenient as on side part (as User Guide documents), so I changed it into "outline" now. Nav content on side part will probably be added in the future. Maybe I should change my description of this PR?

No. As you said, the side part is more convenient.

**Comment by jixuan1989** [comment]
Hi, If no more comment (@Genius-pig ), I will merge this PR first, and wait for the new website in the future.
@samperson1997 , if you have a plan to move the outline from the top to the left side, pls open an issue so that it can remind us.

**Comment by samperson1997** [comment]
> Hi, If no more comment (@Genius-pig ), I will merge this PR first, and wait for the new website in the future.
> @samperson1997 , if you have a plan to move the outline from the top to the left side, pls open an issue so that it can remind us.

Sure, here is the issue: [IOTDB-132](https://issues.apache.org/jira/browse/IOTDB-132).

**Pull request merged**
