### PR TITLE
[IOTDB-149]  Fix wrong Windows path.

### PR DESCRIPTION
**Pull request by Genius-pig**
Fix wrong Windows path and a small Chinese grammar mistake. [IOTDB-149](https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-149?filter=allopenissues)

### CODE REVIEW

**Comment by jixuan1989** [comment]
Hi, you can merge or rebase the master branch again to fix Travis-CI error.

**Comment by Genius-pig** [comment]
OK, I have already rebased it.

**Comment by qiaojialin** [comment]
please fix the conflicts

**Comment by Genius-pig** [comment]
@qiaojialin Already fixed.

**Comment by samperson1997** [comment]
Hi, there are some others' commits and changed files mixed in this PR during your conflict solving. You can simply reset and stage the changes in this PR, and use `git pull --rebase xxx` command to pull and rebase on the latest codes. Then by unstaging and force pushing, there will only be your own changes in this PR :-)

**Pull request merged**
