### PR TITLE
[IOTDB-506]upgrade the protocol to v2 to reject clients or servers that version < 0.10

### PR DESCRIPTION
**Pull request by jixuan1989**
- If users use client/jdbc/session that version <0.10 to connect IoTDB server 0.10, unfriendly exception will be thrown.
- If users use client/jdbc/session that version = 0.10 to connect IoTDB server that version <0.10, unfriendly exception will also be thrown.

So, I upgrade the protocol to V2 while it is V1 in 0.9 and no such field in 0.8.
Then, 
if we use client 0.9 to connect IoTDB 0.10, 

```
IoTDB> Can not establish connection with jdbc:iotdb://127.0.0.1:6667/. Host is 127.0.0.1, port is 6667.
```
(we have no method to change the output of 0.9 client unless we release a new version of 0.9.*).

if we use client 0.10 to connect IoTDB 0.9, 
```
IoTDB> Can not establish connection with jdbc:iotdb://127.0.0.1:6667/ : You may try to connect an old version IoTDB instance using a client with new version: Required field 'client_protocol' was not present! Struct: TSOpenSessionReq(client_protocol:null, username:root, password:root).  Host is 127.0.0.1, port is 6667.
```

### CODE REVIEW

**Comment by jixuan1989** [comment]
Hi @vesense , can you have a look?

**Comment by vesense** [comment]
@jixuan1989 I will take a look tomorrow.

**Comment by vesense** [comment]
I checked the following scenes.

* use client 0.9 to connect server 0.10
* use client 0.10 to connect server 0.9

It's within expectations.
Thanks @jixuan1989  +1 for merging into master.

**Comment by vesense** [comment]
I checked the following scenes.

* use client 0.9 to connect server 0.10
* use client 0.10 to connect server 0.9

It's within expectations.
Thanks @jixuan1989  +1 for merging into master.

**Comment by vesense** [comment]
I checked the following scenes.

* use client 0.9 to connect server 0.10
* use client 0.10 to connect server 0.9

It's within expectations.
Thanks @jixuan1989  +1 for merging into master.

**Pull request merged**
