### PR TITLE
[IOTDB-798] [To rel/0.10] fix a set rowLimit and rowOffset bug

### PR DESCRIPTION
**Pull request by HTHou**
https://github.com/apache/incubator-iotdb/issues/1505

### CODE REVIEW

**Comment by qiaojialin** [comment]
It seems that limit is not supported in group by fill

**Comment by HTHou** [comment]
> It seems that limit is not supported in group by fill

Sure, fixed~ Thanks!

**Comment by qiaojialin** [comment]
This is a bug fix of group by. We'd better to support limit in group by fill also.

Besides, I prefer to set the limit and offset in one place, not in each query type

**Comment by HTHou** [comment]
> We'd better to support limit in group by fill also.

Yes, we can support it in 0.11. 

> Besides, I prefer to set the limit and offset in one place, not in each query type

Fixed, please take a look.

**Comment by HTHou** [comment]
> This is a bug fix of group by. We'd better to support limit in group by fill also.
> 
> Besides, I prefer to set the limit and offset in one place, not in each query type

I updated the antlr part to support limit in group by fill.

**Pull request merged**
