### PR TITLE
[IOTDB-929] Update show timeseries information in readme

### PR DESCRIPTION
**Pull request by yuqi1129**

### CODE REVIEW

**Review by HTHou — COMMENTED** [review]
Very good job. 
It may be not related to this PR, but I would like to mention the link at line 300 of `README.md` should be fixed. It will be great if you can change it. Thanks.

**Comment by yuqi1129** [comment]
@HTHou , No problem, I will update this PR later

**Review by samperson1997 — APPROVED** [review]
Thanks for this vital fix!

**Review by Alima777 — APPROVED** [review]
Nice work~ One suggestion is that force-push every time is not a good way especially in a big patch... as we can not see the changes of each commit.

**Comment by yuqi1129** [comment]
OK, force-push is indeed not suggested in PR. The reason why i try to
overlap the code before is that i do not want to have too many commit
message.
Till now, Git can squash commits into one, so i do not need to use force
push again, Thanks

Xiangwei Wei <notifications@github.com> 于2020年9月30日周三 下午4:23写道：

**Review by HTHou — APPROVED** [review]

**Pull request merged**
