### PR TITLE
[IOTDB-260] Make paths can concatenate

### PR DESCRIPTION
**Pull request by Genius-pig**
https://issues.apache.org/jira/projects/IOTDB/issues/IOTDB-260
For example, you can use
```
  SELECT status FROM root.ln.wf01.{wt01,wt02}
```
Screen Shot 2019-11-06 at 1 35 45 PM

### CODE REVIEW

**Comment by qiaojialin** [comment]
what if the path contains *, could you handle it correctly?

**Comment by Genius-pig** [comment]
> what if the path contains *, could you handle it correctly?
```
IoTDB> SELECT * FROM root.ln.wf01.{wt01,wt02}
SELECT * FROM root.ln.wf01.{wt01,wt02}
+-----------------------------------+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
|                               Time|     root.ln.wf01.wt01.status|root.ln.wf01.wt01.temperature|     root.ln.wf01.wt02.status|root.ln.wf01.wt02.temperature|
+-----------------------------------+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
|      1970-01-01T08:00:00.100+08:00|                         true|                         null|                         true|                         null|
|      1970-01-01T08:00:00.200+08:00|                        false|                        20.71|                        false|                        20.71|
+-----------------------------------+-----------------------------+-----------------------------+-----------------------------+-----------------------------+
Total line number = 2
It costs 0.096s
```

**Comment by LeiRui** [comment]
Glad to see this pr :)

Two places you need to take care of:
1. Add docs!!!
2. Change the title of this pr to a more appropriate one.

**Comment by Genius-pig** [comment]
> Glad to see this pr :)
> 
> Two places you need to take care of:
> 
> 1. Add docs!!!
> 2. Change the title of this pr to a more appropriate one.

What kind of title do you suggest? I don't think "Make paths can concatenate" is a bad title.

**Comment by LeiRui** [comment]
> What kind of title do you suggest? I don't think "Make paths can concatenate" is a bad title.

 I still insist my opinion. There are many ways to make paths concatenate. For example, when executing `select s1,s2 from root.sg.d0`, the query executor will concatenate the prefix path `root.sg.d0` with the two suffix paths `s1`&`s2`. That's why I think `Make paths can concatenate" is not a good title.

If you need suggestions, I would say like "**support multiple timeseries selection using curly braces in the WHERE clause**".

**Pull request closed without merging**
